##############################################################################
#                        ConRiot Copyright (c) 2013                          #
#           This plugin has been specially developed for ConRiot.            #
#    It may not be distributed or used by anyone other than the copyright    #
#    owner. If you got this file from the internet, please send an email     #
#            with the direct URL to: endain.gaming@gmail.com                 #
##############################################################################

name: ${project.name}
version: ${project.version}
website: http://ConRiot.net
description: Economy module developed for ConRiot
author: [Endain]
main: net.conriot.sona.economy.Economy
depend: [CRM-MySQL]
commands:
  pay:
    description: Make a payment to another player
  bal:
    description: View your current balance
  baltop:
    description: View the top 10 player balances
  eco:
    description: Economy management commands